### ISSUE TITLE
Rename one of the puzzles folder

### ISSUE THREAD

**Issue by IrakliDevelop** [guganems/picturePuzzle#1]
Some dude with big nose is an offending name;

It's called Homunculus loxodontus [Wikipedia Page](https://en.wikipedia.org/wiki/Homunculus_loxodontus)

Please rename the folder.

**Comment by IrakliDevelop** [comment]
Is this project dead?

The supporting team is not doing a good job

**Comment by guganems** [comment]
Yes, this project is dead right now

**Comment by IrakliDevelop** [comment]
I created a pull request which solves this problem: [pull request](https://github.com/guganems/picturePuzzle/pull/2)
